# Binarization

In [20]:
import numpy as np
from sklearn import preprocessing
Input_Array = np.array(
                       [
                         [2.1, -1.9, 5.5], 
                         [-1.5, 2.4, 3.5], 
                         [0.5, -7.9, 5.6], 
                         [5.9, 2.3, -5.8]
                        ]
                       )

In [21]:
data_binarized = preprocessing.Binarizer(threshold=0.5).transform(Input_Array)
print("Binarized Data : ")
data_binarized

Binarized Data :

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

In [22]:
from sklearn import preprocessing
ans = np.array([[1,2,3], [4,5,6]])
data_Binary = preprocessing.Binarizer(threshold=1).transform(ans)
data_Binary

array([[0, 1, 1],
       [1, 1, 1]])

# Mean Removal

In [23]:
print("Mean of the data is :", Input_Array.mean(axis=0))
print("STD of the data is : ", Input_Array.std(axis = 0))
Data_Scaled = preprocessing.scale(Input_Array)
print("Mean Removal : ", Data_Scaled.mean(axis = 0))
print("STD Removal : ", Data_Scaled.std(axis = 0))

Mean of the data is : [ 1.75  -1.275  2.2  ]
STD of the data is :  [2.71431391 4.20022321 4.69414529]
Mean Removal :  [1.11022302e-16 0.00000000e+00 0.00000000e+00]
STD Removal :  [1. 1. 1.]

In [24]:
import pandas as pd
df = pd.read_csv(r'C:\Users\mk744\OneDrive - Poornima University\Desktop\Feature Scaling\Data Files\house-prices.csv')

In [25]:
df.head()

   Home     Price    SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0     1  114300.0  1790.0         2          2       2    No         East
1     2  114200.0  2030.0         4          2       3    No         East
2     3  114800.0  1740.0         3          2       1    No         East
3     4   94700.0  1980.0         3          2       3    No         East
4     5  119800.0  2130.0         3          3       3    No         East

# Convert the data into Numpy Array
- Perform Binarization
- Perfrom Mean Removal

In [26]:
# Convert home columns into np array
nd_array = df[['Home', 'Offers']].values
nd_array

array([[  1,   2],
       [  2,   3],
       [  3,   1],
       [  4,   3],
       [  5,   3],
       [  6,   2],
       [  7,   3],
       [  8,   2],
       [  9,   3],
       [ 10,   3],
       [ 11,   3],
       [ 12,   2],
       [ 13,   4],
       [ 14,   5],
       [ 15,   4],
       [ 16,   1],
       [ 17,   4],
       [ 18,   4],
       [ 19,   1],
       [ 20,   2],
       [ 21,   3],
       [ 22,   4],
       [ 23,   3],
       [ 24,   3],
       [ 25,   2],
       [ 26,   3],
       [ 27,   3],
       [ 28,   2],
       [ 29,   3],
       [ 30,   1],
       [ 31,   3],
       [ 32,   2],
       [ 33,   3],
       [ 34,   4],
       [ 35,   3],
       [ 36,   3],
       [ 37,   2],
       [ 38,   4],
       [ 39,   1],
       [ 40,   2],
       [ 41,   1],
       [ 42,   2],
       [ 43,   3],
       [ 44,   1],
       [ 45,   2],
       [ 46,   3],
       [ 47,   2],
       [ 48,   6],
       [ 49,   2],
       [ 50,   3],
       [ 51,   3],
       [ 52,   3],
       [ 53,   4],
       [ 54,   3],
       [ 55,   3],
       [ 56,   2],
       [ 57,   3],
       [ 58,   3],
       [ 59,   1],
       [ 60,   1],
       [ 61,   1],
       [ 62,   2],
       [ 63,   2],
       [ 64,   2],
       [ 65,   2],
       [ 66,   1],
       [ 67,   4],
       [ 68,   3],
       [ 69,   4],
       [ 70,   3],
       [ 71,   3],
       [ 72,   1],
       [ 73,   3],
       [ 74,   2],
       [ 75,   3],
       [ 76,   2],
       [ 77,   2],
       [ 78,   3],
       [ 79,   3],
       [ 80,   1],
       [ 81,   4],
       [ 82,   2],
       [ 83,   1],
       [ 84,   2],
       [ 85,   3],
       [ 86,   2],
       [ 87,   4],
       [ 88,   1],
       [ 89,   2],
       [ 90,   4],
       [ 91,   2],
       [ 92,   2],
       [ 93,   2],
       [ 94,   2],
       [ 95,   3],
       [ 96,   1],
       [ 97,   3],
       [ 98,   1],
       [ 99,   1],
       [100,   2],
       [101,   5],
       [102,   5],
       [103,   4],
       [104,   3],
       [105,   4],
       [106,   4],
       [107,   4],
       [108,   1],
       [109,   3],
       [110,   3],
       [111,   1],
       [112,   2],
       [113,   2],
       [114,   3],
       [115,   2],
       [116,   3],
       [117,   1],
       [118,   2],
       [119,   3],
       [120,   4],
       [121,   3],
       [122,   3],
       [123,   1],
       [124,   3],
       [125,   3],
       [126,   2],
       [127,   1],
       [128,   4]], dtype=int64)

In [27]:
Input_Binarization = preprocessing.Binarizer(threshold=1).transform(nd_array)
Input_Binarization

array([[0, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1]], dtype=int64)

In [28]:
print("Mean = ", Input_Binarization.mean(axis=0))
print("Std = ", Input_Binarization.std(axis = 0))
Scaled_Values = preprocessing.scale(Input_Binarization)
print("Scaled Mean = ", Scaled_Values.mean(axis = 0))
print("Scaled STD = ", Scaled_Values.std(axis = 0))

Mean =  [0.9921875 0.8203125]
Std =  [0.0880424  0.38392695]
Scaled Mean =  [-6.93889390e-18 -4.16333634e-17]
Scaled STD =  [1. 1.]

In [29]:
df.head(2)

   Home     Price    SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0     1  114300.0  1790.0         2          2       2    No         East
1     2  114200.0  2030.0         4          2       3    No         East

In [30]:
data = df[['Bedrooms', 'Bathrooms']].to_numpy()
data

array([[2, 2],
       [4, 2],
       [3, 2],
       [3, 2],
       [3, 3],
       [3, 2],
       [3, 3],
       [4, 2],
       [4, 2],
       [3, 3],
       [3, 2],
       [2, 2],
       [3, 2],
       [3, 3],
       [4, 3],
       [4, 2],
       [3, 3],
       [3, 3],
       [2, 2],
       [3, 3],
       [3, 2],
       [3, 2],
       [3, 2],
       [3, 2],
       [4, 3],
       [4, 3],
       [4, 2],
       [3, 2],
       [2, 2],
       [4, 3],
       [4, 3],
       [2, 2],
       [3, 3],
       [5, 3],
       [2, 2],
       [3, 3],
       [2, 2],
       [4, 3],
       [3, 2],
       [3, 2],
       [2, 2],
       [4, 3],
       [2, 2],
       [3, 2],
       [3, 3],
       [3, 2],
       [2, 3],
       [3, 2],
       [2, 2],
       [3, 2],
       [3, 2],
       [2, 2],
       [2, 3],
       [3, 2],
       [3, 2],
       [2, 2],
       [3, 2],
       [4, 3],
       [3, 3],
       [4, 2],
       [3, 3],
       [2, 2],
       [4, 3],
       [2, 3],
       [3, 2],
       [2, 2],
       [3, 3],
       [4, 3],
       [3, 2],
       [4, 3],
       [3, 3],
       [4, 2],
       [3, 2],
       [3, 3],
       [3, 3],
       [2, 2],
       [3, 2],
       [4, 3],
       [3, 2],
       [4, 2],
       [3, 3],
       [4, 3],
       [2, 2],
       [3, 3],
       [2, 2],
       [4, 3],
       [4, 2],
       [3, 3],
       [3, 3],
       [2, 2],
       [4, 2],
       [3, 2],
       [3, 2],
       [3, 3],
       [4, 3],
       [2, 2],
       [3, 3],
       [2, 2],
       [3, 2],
       [3, 3],
       [3, 2],
       [3, 3],
       [3, 3],
       [4, 3],
       [3, 2],
       [4, 3],
       [3, 2],
       [3, 2],
       [3, 3],
       [3, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [3, 2],
       [4, 3],
       [3, 3],
       [5, 4],
       [3, 2],
       [3, 2],
       [2, 2],
       [2, 3],
       [3, 3],
       [2, 2],
       [3, 3],
       [4, 3],
       [2, 2],
       [3, 3],
       [3, 3]], dtype=int64)

# Perfrom Binarization on Bedrooms and Bathrooms Features

In [31]:
Input_Binary = preprocessing.Binarizer(threshold=2).transform(data)
Input_Binary

array([[0, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1]], dtype=int64)

In [32]:
print("Mean = ", Input_Binary.mean(axis = 0))
print("STD = ", Input_Binary.std(axis = 0))
Scaled_Mean = preprocessing.scale(Input_Binary)
print("Scaled Mean = ", Scaled_Mean.mean(axis = 0))
print("Scaled STD = ", Scaled_Mean.std(axis = 0))

Mean =  [0.765625 0.4375  ]
STD =  [0.42360755 0.49607837]
Scaled Mean =  [ 6.24500451e-17 -5.55111512e-17]
Scaled STD =  [1. 1.]

# MinMax Scalar

In [33]:
data_minmax_scalar = preprocessing.MinMaxScaler(feature_range=(0,1))
data_minmax_scaled = data_minmax_scalar.fit_transform(Input_Binary) 
data_minmax_scaled.astype('int')

array([[0, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1]])